fx_version 'cerulean'
game 'gta5'
author 'SzCode / SzCore'
version '1.4.0-rc1'
description 'SzCore ambient world, population and dispatch controller'
shared_script 'config.lua'
client_script 'client/main.lua'
server_script 'server/main.lua'
dependency 'szcore'
